// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using schoolApi.Data;

#nullable disable

namespace schoolApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260426144924_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("schoolApi.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Register")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Classroom");
                });

            modelBuilder.Entity("schoolApi.Models.ClassroomSubjectMatter", b =>
                {
                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectMatterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("ENUM('Monday', 'Tuesday', 'Wednesday', 'Thusday', 'Friday', 'Saturday', 'Sunday', 'Undefined') DEFAULT 'Undefined'");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EndedAt")
                        .HasColumnType("TIME");

                    b.Property<Guid>("Register")
                        .HasColumnType("char(36)");

                    b.Property<TimeSpan>("StartedAt")
                        .HasColumnType("TIME");

                    b.HasKey("ClassroomId", "SubjectMatterId");

                    b.HasIndex("SubjectMatterId");

                    b.ToTable("ClassroomSubjectMatter");
                });

            modelBuilder.Entity("schoolApi.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Register")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("schoolApi.Models.CourseSubjectMatter", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectMatterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("IsActived")
                        .HasColumnType("TINYINT(1) NOT NULL DEFAULT 0");

                    b.Property<sbyte>("IsMandatory")
                        .HasColumnType("TINYINT(1) NOT NULL DEFAULT 0");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("WorkloadHours")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "SubjectMatterId");

                    b.HasIndex("SubjectMatterId");

                    b.ToTable("CourseSubjectMatter");
                });

            modelBuilder.Entity("schoolApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("INT NOT NULL");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Register")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("schoolApi.Models.StudentSubjectMatter", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectMatterId")
                        .HasColumnType("int");

                    b.Property<decimal>("FirstGrade")
                        .HasColumnType("DECIMAL(4, 2) CHECK (FirstGrade <= 10) DEFAULT 0");

                    b.Property<decimal>("GradeTotal")
                        .HasColumnType("DECIMAL(4, 2) CHECK (GradeTotal <= 10) DEFAULT 0");

                    b.Property<Guid>("Register")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("SecondGrade")
                        .HasColumnType("DECIMAL(4, 2) CHECK (SecondGrade <= 10) DEFAULT 0");

                    b.HasKey("StudentId", "SubjectMatterId");

                    b.HasIndex("SubjectMatterId");

                    b.ToTable("StudentSubjectMatter");
                });

            modelBuilder.Entity("schoolApi.Models.SubjectMatter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Register")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("SubjectMatter");
                });

            modelBuilder.Entity("schoolApi.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("INT NOT NULL");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Register")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("schoolApi.Models.ClassroomSubjectMatter", b =>
                {
                    b.HasOne("schoolApi.Models.Classroom", null)
                        .WithMany("ClassroomSubjectMatters")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("schoolApi.Models.SubjectMatter", null)
                        .WithMany("ClassroomSubjectMatters")
                        .HasForeignKey("SubjectMatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("schoolApi.Models.CourseSubjectMatter", b =>
                {
                    b.HasOne("schoolApi.Models.Course", null)
                        .WithMany("CourseSubjectMatters")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("schoolApi.Models.SubjectMatter", null)
                        .WithMany("CourseSubjectMatters")
                        .HasForeignKey("SubjectMatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("schoolApi.Models.Student", b =>
                {
                    b.HasOne("schoolApi.Models.Course", null)
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("schoolApi.Models.StudentSubjectMatter", b =>
                {
                    b.HasOne("schoolApi.Models.Student", null)
                        .WithMany("StudentSubjectMatters")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("schoolApi.Models.SubjectMatter", null)
                        .WithMany("StudentSubjectMatters")
                        .HasForeignKey("SubjectMatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("schoolApi.Models.SubjectMatter", b =>
                {
                    b.HasOne("schoolApi.Models.Teacher", null)
                        .WithMany("SubjectMatters")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("schoolApi.Models.Classroom", b =>
                {
                    b.Navigation("ClassroomSubjectMatters");
                });

            modelBuilder.Entity("schoolApi.Models.Course", b =>
                {
                    b.Navigation("CourseSubjectMatters");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("schoolApi.Models.Student", b =>
                {
                    b.Navigation("StudentSubjectMatters");
                });

            modelBuilder.Entity("schoolApi.Models.SubjectMatter", b =>
                {
                    b.Navigation("ClassroomSubjectMatters");

                    b.Navigation("CourseSubjectMatters");

                    b.Navigation("StudentSubjectMatters");
                });

            modelBuilder.Entity("schoolApi.Models.Teacher", b =>
                {
                    b.Navigation("SubjectMatters");
                });
#pragma warning restore 612, 618
        }
    }
}
